# Configuration file which specifies all of the packages to install to set up a conda environment

name: ml-devs
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- flask
- joblib
- lime
- matplotlib
- nltk
- pandas
- pandas-profiling
- python>=3
- rise
- scikit-learn=0.20.2
- seaborn
- pip:
  - version-information
