# Configuration file which specifies all of the packages to install to set up a conda environment

name: ml-workshops
channels:
- anaconda
- conda-forge
- defaults
dependencies:
- flask
- graphviz # dl: used to plot Keras model
- hyperopt=0.1.2 # ml-advanced
- ipykernel
- joblib
- kaggle
- lime # optional - prediction explanations
- matplotlib # for plots
- nltk # optional - for text pre-processing
- pandas
- pandas-profiling
- papermill # for notebook parametrization and execution from CLI
- pip
- pydot # dl: used to plot Keras model
- pylint # used by VS Code for linting
- python>=3
- rope # used by VS Code for refactoring
- rise # slideshow mode on notebooks
- seaborn # for plots
- version_information
- xgboost # ml-advanced
- pip:
  - h5py==2.8.0rc1 # dl
  - networkx==1.11 # ml-advanced — see https://github.com/hyperopt/hyperopt/issues/325
  - python-dotenv
  - scikit-learn==0.21.3
  - tf-nightly-2.0-preview # dl